server:
	$(CXX) server.cpp -o server.out -std=c++11 -O2 -I ../../../ -I ../../../re2 -I ../../../mongoose ../../../mongoose/mongoose.c -l boost_filesystem -l boost_system -l boost_iostreams -L ../../../re2/obj -l re2 -l pthread -l dl
