server:
	$(CXX) server.cpp -o server.out -std=c++11 -Ofast -march=native -I ../../../ -l boost_filesystem -l boost_system -I ../../../mongoose ../../../mongoose/mongoose.c -I ../../../re2 -L ../../../re2/obj -l re2 -l gflags -l pthread -l dl
